//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/// <remarks>
/// si type = TRESOR alors nbTresor>=0,
/// sinon nbTresor = 0
/// </remarks>
class Case
{
	private :

		int nbTresor;

	protected :


	public :


	private :


	protected :


	public :

		virtual void prendreTresor();
		Case(Type t, int n);
		virtual TypeCase getType();

}; 

