//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

class DeplacementBateau : public State {abstract}
{
	private :

	public :

		DeplacementBateau();
		override void gerer();

}; 

