#ifndef ENUMERATIONS_H
#define ENUMERATIONS_H

#define LARGEUR_PLATEAU 11
#define HAUTEUR_PLATEAU 8

typedef enum {ATTENTE_NB_JOUEURS, CHOIX_COULEUR, LANCER_DE, DEPLACEMENT_BATEAU, TIR_CASE_CANON, TIR_BORDURE} TypeEtat;
typedef enum {CARAVELLE, FREGATE, RADEAU}  TypeBateau;
typedef enum {EAU, ILE, CANON, TRESOR} TypeCase;

#endif