//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

class Joueur
{
	private :

		int nbTresorPort;
		int bateauCourant;

	public :

		virtual TypeBateau getTypeBateau();

}; 

