//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include <utility>
#include "State.h"
#include "Moteur.h"

using namespace std;

class Tir : public State
{
	private :
		int angle;
		int puissance;
		pair<int,int> direction;

		pair<int,int> tirer(); // retourne l'impact du tir
		pair<int,int> calculerTir(); // calcule la portée du tir

	public :

		Tir(Moteur* m);
		bool reglerDirectionTir(int i, int j);
		bool reglerTir(int p, int a);
		void gerer(); // gere les conséquences du tir sur le jeu
		void initialiserTir(int angle, int puissance);

}; 

