//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

class TirBordure : public Tir
{
	private :


	protected :


	public :


	private :


	protected :


	public :

		override void gerer();
		TirBordure();

}; 

