//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "State.h"
class AttenteNbJoueurs : public State
{
	private :


	protected :


	public :


	private :


	protected :


	public :

		void gerer();

}; 

