//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include <utility>
#include "enumerations.h"

using namespace std;

class Bateau
{
	private :

		int posX;
		int posY;
		int nbTresor;
		TypeBateau type;

	protected :


	public :


	private :


	protected :


	public :
		Bateau();
		void init_port(int port);
		void ajouterTresor();
		void enleverTresor();
		void changerPosition(int x, int y);
		TypeBateau getType();
		pair<int,int> getPosition();

}; 

