//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

class LancerDe : public State
{
	private :


	protected :


	public :


	private :

		vector <pair <int,int> > casesAccessibles();

	protected :


	public :

		override void gerer();

}; 

