//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/// <remarks>Les cases sont stockées dans un vecteur à 2 dimensions</remarks>
class Map
{
	private :



	public :

		/*TypeCase getTypeCase(int x, int y);*/

}; 

