//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/// <remarks>Les cases sont stockées dans un vecteur à 2 dimensions</remarks>
#include <vector>
#include "Case.h"
#include "enumerations.h"

using namespace std;

class Map
{
	private :
		vector<Case> cases;


	public :
		Map();
		TypeCase getTypeCase(int x, int y);

}; 

