//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

class Tir : public State
{
	private :

		int angle;
		int puissance;

	protected :


	public :


	private :

		bool calculResTir();

	protected :


	public :

		Tir();
		abstract void gerer();
		virtual void initialiserTir(int angle, int puissance);

}; 

